export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";

export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_PRODUCTS_ERROR = "UPDATE_PRODUCTS_ERROR";

export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const DELETE_PRODUCTS_ERROR = "DELETE_PRODUCTS_ERROR";

export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const ADD_PRODUCTS_ERROR = "ADD_PRODUCTS_ERROR";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const CATEGORIES_ERROR = "CATEGORIES_ERROR";

export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const ADD_CATEGORIES_ERROR = "ADD_CATEGORIES_ERROR";

export const DELETE_CATEGORIES = "DELETE_CATEGORIES";
export const DELETE_CATEGORIES_ERROR = "DELETE_CATEGORIES_ERROR";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CATEGORIES_ERROR = "UPDATE_CATEGORIES_ERROR";

export const GET_USERS = "GET_USERS";
export const USERS_ERROR = "USERS_ERROR";

export const SHOW_EDIT_MODAL = "SHOW_EDIT_MODAL";
export const SHOW_EDIT_MODAL_ERROR = "SHOW_EDIT_MODAL_ERROR";

export const HIDE_EDIT_MODAL = "HIDE_EDIT_MODAL";
export const HIDE_EDIT_MODAL_ERROR = "HIDE_EDIT_MODAL_ERROR";

export const SHOW_LOADING = "SHOW_LOADING";
export const SHOW_LOADING_ERROR = "SHOW_LOADING_ERROR";
export const HIDE_LOADING = "HIDE_LOADING";
export const HIDE_LOADING_ERROR = "HIDE_LOADING_ERROR";

export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_ERROR_FAILED = "CLEAR_ERROR_FAILED";
export const SHOW_ERROR = "SHOW_ERROR";
export const SHOW_ERROR_FAILED = "SHOW_ERROR_FAILED";
export const GET_ERROR = "GET_ERROR";
export const GET_ERROR_FAILED = "GET_ERROR_FAILED";

export const SHOW_LOADING_CATEGORIES = "SHOW_LOADING";
export const HIDE_LOADING_CATEGORIES = "HIDE_LOADING";
export const CLEAR_ERROR_CATEGORIES = "CLEAR_ERROR";
export const SHOW_ERROR_CATEGORIES = "SHOW_ERROR";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_FROM_CART_ERROR = "REMOVE_FROM_CART_ERROR";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

export const CLEAR_CART = "CLEAR_CART";
export const SET_ORDERED_ITEM = "SET_ORDERED_ITEM";

export const SET_TO_SELECTED = "SET_TO_SELECTED";
export const CLEAR_SELECTED = "CLEAR_SELECTED";

export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const GET_PRODUCTS_BY_CATEGORY_ERROR = "GET_PRODUCTS_BY_CATEGORY_ERROR";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SHOW_LOADING_LOGIN = "SHOW_LOADING_LOGIN";
export const SHOW_LOADING_LOGIN_ERROR = "SHOW_LOADING_LOGIN_ERROR";
export const HIDE_LOADING_LOGIN = "HIDE_LOADING_LOGIN";
export const HIDE_LOADING_LOGIN_ERROR = "HIDE_LOADING_LOGIN_ERROR";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

