export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";

export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_PRODUCTS_ERROR = "UPDATE_PRODUCTS_ERROR";

export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const DELETE_PRODUCTS_ERROR = "DELETE_PRODUCTS_ERROR";

export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const ADD_PRODUCTS_ERROR = "ADD_PRODUCTS_ERROR";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const CATEGORIES_ERROR = "CATEGORIES_ERROR";

export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const ADD_CATEGORIES_ERROR = "ADD_CATEGORIES_ERROR";

export const DELETE_CATEGORIES = "DELETE_CATEGORIES";
export const DELETE_CATEGORIES_ERROR = "DELETE_CATEGORIES_ERROR";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";

export const GET_USERS = "GET_USERS";
export const USERS_ERROR = "USERS_ERROR";

export const SHOW_EDIT_MODAL = "SHOW_EDIT_MODAL";
export const SHOW_EDIT_MODAL_ERROR = "SHOW_EDIT_MODAL_ERROR";

export const HIDE_EDIT_MODAL = "HIDE_EDIT_MODAL";
export const HIDE_EDIT_MODAL_ERROR = "HIDE_EDIT_MODAL_ERROR";

export const SHOW_LOADING = "SHOW_LOADING";
export const SHOW_LOADING_ERROR = "SHOW_LOADING_ERROR";
export const HIDE_LOADING = "HIDE_LOADING";
export const HIDE_LOADING_ERROR = "HIDE_LOADING_ERROR";

export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_ERROR_FAILED = "CLEAR_ERROR_FAILED";
export const SHOW_ERROR = "SHOW_ERROR";
export const SHOW_ERROR_FAILED = "SHOW_ERROR_FAILED";
export const GET_ERROR = "GET_ERROR";
export const GET_ERROR_FAILED = "GET_ERROR_FAILED";
